baseURL = "https://ryluiiwan.com"
title = "Ryluiiwan"
theme = "hugo-PaperMod"
enableEmoji = true
hasCJKLanguage = true
rssLimit = 20

[pagination]
  pagerSize = 20
  path = "page"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[author]
  name = "Nuoyi Lu"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  categories = "/category/:slug/"
  tags = "/tag/:slug/"
  pages = "/:slug/"

[params]
  since = "2024"
  env = "production"
  description = "Be better"
  keywords = ["marketing", "programming", "python", "blog"]
  DateFormat = "2006-01-02"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  comments = true

  [params.homeInfoParams]
    Title = "RYLUIIWAN"
    Content = "Impact-Site-Verification: e565516b-455f-49f6-b260-f6ebe8f25efc\n\nBe better"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/oyeahshalala/"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/Lunuoyi"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ryluiiwan348@gmail.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ryluiiwan"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = false

# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  threshold = 50
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 200

[[related.indices]]
  name = "keywords"
  weight = 150

[[related.indices]]
  name = "tags"
  weight = 100

# ------------------------------------- #
# ---- Languages ---------------------- #
# ------------------------------------- #

[languages.zh]
  languageCode = "zh"
  languageName = "中文"
  contentDir = "content/zh"
  weight = 1

  [languages.zh.params]
    description = "Be better"

    [languages.zh.params.homeInfoParams]
      Title = "RYLUIIWAN"
      Content = "Impact-Site-Verification: e565516b-455f-49f6-b260-f6ebe8f25efc\n\nBe better"

  [[languages.zh.menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[languages.zh.menu.main]]
    name = "思考"
    url = "category/thinking/"
    weight = 10

  [[languages.zh.menu.main]]
    name = "工具"
    url = "category/tools/"
    weight = 20

  [[languages.zh.menu.main]]
    name = "学习"
    url = "category/learning/"
    weight = 30

  [[languages.zh.menu.main]]
    name = "标签"
    url = "tags/"
    weight = 40

  [[languages.zh.menu.main]]
    name = "归档"
    url = "archives/"
    weight = 50

[languages.en]
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  weight = 2

  [languages.en.params]
    description = "Be better"

    [languages.en.params.homeInfoParams]
      Title = "RYLUIIWAN"
      Content = "Impact-Site-Verification: e565516b-455f-49f6-b260-f6ebe8f25efc\n\nBe better"

  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[languages.en.menu.main]]
    name = "Thinking"
    url = "category/thinking/"
    weight = 10

  [[languages.en.menu.main]]
    name = "Learning"
    url = "category/learning/"
    weight = 20

  [[languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 40

  [[languages.en.menu.main]]
    name = "Archives"
    url = "archives/"
    weight = 50
